import ctypes
from numpy.ctypeslib import ndpointer


def getLocation():

    # use the shared library generated by skyhookpl/getlocation.c
    getloc = ctypes.CDLL("skyhookpl/libgetloc.so")

    # use the ndpointer function provided by numpy, and pass the expected array datatype and the expected size of the same array
    # use this to set the value of restype, which will help identify the datatype of the return value of the C function
    getloc.getLocation.restype = ndpointer(dtype=ctypes.c_double, shape=(2,))

    # store the coordinates array of type double returned by the function defined by getlocation.c as a list in result
    # and return it to the calling function
    result = getloc.getLocation()
    return result
