import ctypes
import time
from numpy.ctypeslib import ndpointer
from writeToDB import write

while True:

    # use the shared library generated by skyhookpl/getlocation.c
    getloc = ctypes.CDLL("skyhookpl/libgetloc.so")

    # use the ndpointer function provided by numpy, and pass the expected array datatype and the expected size of the same array
    # use this to set the value of restype, which will help identify the datatype of the return value of the C function
    getloc.getLocation.restype = ndpointer(dtype=ctypes.c_double, shape=(2,))

    # store the coordinates array of type double returned by the function defined by getlocation.c as a list in result
    # and return it to the calling function
    result = getloc.getLocation()
    write("Latitude", result[0])
    write("Longitude", result[1])

    # print the values if you need to
    print(f"Latitude : {result[0]}, Longitude : {result[1]}")
    time.sleep(300)

